### PR TITLE
Extra packages installation

### PR DESCRIPTION
**Pull request by salva09**
I'm thinking if this feature it's okay in the advanced options, or maybe could be better to show a prompt during the installation "Would you like to install an extra packages?", so the average user could install the packages listed there.

### CODE REVIEW

**Comment by salva09** [comment]
@paperbenni what do you think?

**Comment by paperbenni** [comment]
single quote the multiline text and prompt and double quote the whole command defining the variable

**Comment by paperbenni** [comment]
And I'll maybe change some of the packages available but other than that, it's very mergeable :)

**Comment by salva09** [comment]
Thank you :') And what about taking it out from advanced and put it in the normal installation flow?

**Comment by paperbenni** [comment]
The normal installation flow asks things that concern the OS installation and are needed to install. It should be possible to install instantOS as a "normal" user that wants to browse the web, do emails or gaming. There needs to be no "I don't know what to choose here and will quit because I don't want to mess anything up" moment. So no, it won't get added as a mandatory step because it is not mandatory and would add unnecessary complexity for people who don't need it.

**Pull request merged**
